descriptor-schema-version: "2.12"

info:
  name: iox-x86-hello-world
  description: "Small Linux hello world"
  version: "1.1"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  type: docker
  cpuarch: x86_64
  resources:
    profile: custom
    cpu: 100
    memory: 32
    disk: 10

    network:
      -
        interface-name: eth0
  # Specify runtime and startup
  startup:
    runtime_options: ""
    rootfs: rootfs.tar
    target: ['/bin/sh', '/start.sh']    